src/Entity/Video.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 */
class Video
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CategoriaVideo", inversedBy="videos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categoria;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Image",cascade={"persist"})
     */
    private $imagen;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $duracion;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_vimeo;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $es_gratis;

    /**
     * @ORM\Column(type="integer")
     */
    private $orden;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $visible;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $id_preview_vimeo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $resumen;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $destacado;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $aws_url;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $aws_preview_url;

    public function __construct()
    {
        $this->updated_at = new \DateTime();
    }

    public function __toString()
    {
        return $this->getTitulo();
    }

    /**
     * @Groups({"searchable"})
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }



    public function getCategoria(): ?CategoriaVideo
    {
        return $this->categoria;
    }

    public function setCategoria(?CategoriaVideo $categoria): self
    {
        $this->categoria = $categoria;

        return $this;
    }

    public function getImagen(): ?Image
    {
        return $this->imagen;
    }

    public function setImagen(?Image $imagen): self
    {
        $this->imagen = $imagen;

        return $this;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getDuracion(): ?string
    {
        return $this->duracion;
    }

    public function setDuracion(string $duracion): self
    {
        $this->duracion = $duracion;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getIdVimeo(): ?string
    {
        return $this->id_vimeo;
    }

    public function setIdVimeo(string $id_vimeo): self
    {
        $this->id_vimeo = $id_vimeo;

        return $this;
    }

    public function getEsGratis(): ?bool
    {
        return $this->es_gratis;
    }

    public function setEsGratis(?bool $es_gratis): self
    {
        $this->es_gratis = $es_gratis;

        return $this;
    }

    public function getOrden(): ?int
    {
        return $this->orden;
    }

    public function setOrden(int $orden): self
    {
        $this->orden = $orden;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(?bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(?string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getIdPreviewVimeo(): ?string
    {
        return $this->id_preview_vimeo;
    }

    public function setIdPreviewVimeo(?string $id_preview_vimeo): self
    {
        $this->id_preview_vimeo = $id_preview_vimeo;

        return $this;
    }

    public function getResumen(): ?string
    {
        return $this->resumen;
    }

    public function setResumen(?string $resumen): self
    {
        $this->resumen = $resumen;

        return $this;
    }

    public function getDestacado(): ?bool
    {
        return $this->destacado;
    }

    public function setDestacado(?bool $destacado): self
    {
        $this->destacado = $destacado;

        return $this;
    }

    public function getAwsUrl(): ?string
    {
        return $this->aws_url;
    }

    public function setAwsUrl(?string $aws_url): self
    {
        $this->aws_url = $aws_url;

        return $this;
    }

    public function getAwsPreviewUrl(): ?string
    {
        return $this->aws_preview_url;
    }

    public function setAwsPreviewUrl(?string $aws_preview_url): self
    {
        $this->aws_preview_url = $aws_preview_url;

        return $this;
    }
}

templates/basic/aws_video.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{#    <form action="{{ path('buscador') }}">#}
{#        <input id="query" name="query" />#}
{#    </form>#}
    <link href="https://vjs.zencdn.net/7.2.3/video-js.css" rel="stylesheet">

    <div class="container-fluid px-0 bg-blue min-vh-100  pb-footer bg-videos">

        <div class="">
            {#Este deberia ser un tipo especial de video con:
             *texto enriquecido
             *2 espacios para links de vimeo
                Uno para el preview y otro para el video completo al que enlaza
             *
             #}
            <p>https://d2ni8vd6etkcfg.cloudfront.net/assets/361dc059-0a26-48ab-9cfd-7312fdc50ad9/HLS/test.m3u8</p>


            <video id='hls-example'  class="video-js vjs-default-skin" width="400" height="300" controls data-src="https://d2ni8vd6etkcfg.cloudfront.net/assets/361dc059-0a26-48ab-9cfd-7312fdc50ad9/HLS/test.m3u8">

            </video>

        </div>
    </div>


{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
    <script>


        var video = document.getElementById('hls-example');
        var videoSrc = 'https://d2ni8vd6etkcfg.cloudfront.net/assets/361dc059-0a26-48ab-9cfd-7312fdc50ad9/HLS/test.m3u8';
        if (Hls.isSupported()) {
            console.log("comaws 1");
            var hls = new Hls();
            hls.loadSource(videoSrc);
            hls.attachMedia(video);
            hls.on(Hls.Events.MANIFEST_PARSED, function() {
                video.play();
            });
        }else if (video.canPlayType('application/vnd.apple.mpegurl')) {
            console.log("comaws 2");
            video.src = videoSrc;
            video.addEventListener('loadedmetadata', function() {
                video.play();
            });
        }
    </script>
{% endblock %}

templates/basic/cancelarSuscripcion.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <script
            src="https://www.paypal.com/sdk/js?client-id=AfnIeZFch5lhzPRXhGAqvqfOyk8Bng_hpFjKW5tE8CHGZ50Fz0je2TTZ1VpxvKFYKAyRN4Sq8K5hfdLn&vault=true">
    </script>
    {{ include('global/header-user.html.twig') }}

    <div class="container-fluid pb-footer">
        <div class="bg-2 p-3">
            <div>
                <div class="bg-3">
                    <section class="pt-header pb-footer" id="suscribirse">
                        <div class="wp text-center border-brown-3 py-5">
                            <img class="w-50" src="{{ asset('images/suscribete.png') }}"/>


                            <div class="form-group">
                                <p>{{ qi.textoBig('cancelar_suscripcion_text') }}</p>
                                <a class="" href="{{ path('make-cancelacion') }}">{{ qi.texto('cancelar_suscripcion') }}</a>
                            </div>


                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/basic/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ include('global/header-log.html.twig') }}

    <section class="banner-full">
        <div class="s-wp text-center">
            <img class="logo w-50" src="{{ asset('images/logo-h.png') }}"/>
            <h3 class="my-md-5 mb-xs-3">{{ qi.texto('el_canal_mas_top') }}</h3>
            <a class="bt-1" href="{{ path('fos_user_registration_register') }}">{{ qi.texto('suscribirse') }}</a>
        </div>
    </section>

    <div class="container-fluid p-0">
        <div class="bg-2 p-3">
            <div class="border-brown-3">
                <section class="cont-item-channel d-flex justify-content-md-between align-content-md-center position-relative">
                    <img class="b-d" src="{{ asset('images/border-dash-1.png') }}"/>
                    <div class="wp text-center py-md-5">
                        <a class="item-channel  my-3 my-md-5"><img class="w-100" src="{{ asset('images/live-show.png') }}"/></a>
                        <a class="item-channel  my-3 my-md-5"><img class="w-100" src="{{ asset('images/politicamente-incorrecto.png') }}"/></a>
                        <a class="item-channel  my-3 my-md-5"><img class="w-100" src="{{ asset('images/boletin-del-gomelo.png') }}"/></a>
                        <a class="item-channel  my-3 my-md-5"><img class="w-100" src="{{ asset('images/juanois-experience.png') }}"/></a>
                        <br>
                        <p class="my-md-5">{{ qi.textoBig('texto_logos') }}</p>
                        <a class="bt-1 py-1" href="{{ path('fos_user_registration_register') }}">{{ qi.texto('suscribirse') }}</a>
                    </div>
                    <img class="b-d" src="{{ asset('images/border-dash-1.png') }}"/>
                </section>
                <div class="bg-3 pb-footer opciones-log">
                    <section class="d-md-flex justify-content-md-center align-items-center">
                        <div class="celular w-25 d-none d-md-inline-block py-5"><img class="w-75 float-right" src="{{ asset('images/celular.png') }}"/></div>
                        <div class="wp p-4 text-center">
                            <h2>{{ qi.texto('titulo_iphone_mac') }}</h2>
                            <p>{{ qi.textoBig('texto_ihpone_mac')|raw }}</p>
                            <a class="bt-1 mr-0 mr-md-3" href="{{ path('fos_user_security_login') }}">{{ qi.texto('iniciar_sesion') }}</a>
                            <a class="bt-1" href="{{ path('fos_user_registration_register') }}">{{ qi.texto('suscribirse') }}</a>
                        </div>
                        <div class="compu w-25 d-none d-md-inline-block py-5"><img class="w-100" src="{{ asset('images/compu.png') }}"/></div>
                    </section>
                    <section class="d-md-flex justify-content-md-center align-items-center">
                        <div class="wp p-4 text-center">
                            <h2>{{ qi.texto('preguntas_frequentes') }}</h2>
                            {% for p  in faqs %}
                               <div class="contFaq">
                                   <div class="pregunta">
                                       <h3>{{ p.pregunta }}</h3>
                                   </div>
                                   <div class="respuesta">
                                       <p>
                                           {{ p.respuesta|nl2br }}
                                       </p>
                                   </div>
                               </div>
                            {% endfor %}




                        </div>
                    </section>
                   {# <section class="pb-5" id="suscribirse">
                        <div class="wp text-center">
                            <img class="w-50" src="{{ asset('images/suscribete.png') }}"/>
                            <form class="text-left pb-footer">
                                <div class="d-md-flex">
                                    <div class="form-group w-50 pr-3">
                                        <label>Nombres</label>
                                        <input type="text"/>
                                    </div>
                                    <div class="form-group w-50 pl-3">
                                        <label>Apellidos</label>
                                        <input type="text"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Correo electrónico</label>
                                    <input type="text"/>
                                </div>
                                <div class="d-md-flex">
                                    <div class="form-group w-50 pr-3">
                                        <label>Contraseña</label>
                                        <input type="text"/>
                                    </div>
                                    <div class="form-group w-50 pl-3">
                                        <label>Confirmar contraseña</label>
                                        <input type="text"/>
                                    </div>
                                </div>
                                <div class="form-group text-center">
                                    <label class="mt-3">
                                        Escoge tu método de pago:
                                    </label>
                                    <label class="w-25 py-5">
                                        <img src="{{ asset('images/payu.png') }}"/>
                                        <br>
                                        <input type="radio" name="pay"/>
                                    </label>
                                    <label class="w-25 py-5">
                                        <img src="{{ asset('images/paypal.png') }}"/>
                                        <br>
                                        <input type="radio" name="pay"/>
                                    </label>
                                </div>
                                <div class="w-75 m-auto px-5">
                                    <div class="d-md-flex">
                                        <div class="form-group w-50 pr-3">
                                            <label>Nombres</label>
                                            <input type="text"/>
                                        </div>
                                        <div class="form-group w-50 pl-3">
                                            <label>Apellido</label>
                                            <input type="text"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Número de tarjeta</label>
                                        <input type="text"/>
                                    </div>
                                    <div class="form-group">
                                        <label>Fecha de vencimiento</label>
                                        <input type="text"/>
                                    </div>
                                    <div class="form-group">
                                        <label>Código de seguridad</label>
                                        <input type="text"/>
                                    </div>
                                    <div class="form-group text-center">
                                        <label><strong>PLAN ESTANDAR</strong> 6  USD</label>
                                        <input type="submit" class="bt-1" value="PAGAR"/>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </section>#}
                </div>
            </div>
        </div>
    </div>





{% endblock %}
{% block javascripts %}
    <script>

    </script>
{% endblock %}

templates/basic/terminos_condiciones.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ include('global/header-user.html.twig') }}
    <section class="banner text-center d-flex justify-content-md-center pb-footer pt-header">
        <div class="border-brown-3 p-4 terminos-condiciones">
            <h2>{{ qi.texto('titulo_terminos_condiciones') }}</h2>
            <div>
                {{ qi.textoBig('terminos_condiciones')|raw }}
            </div>
        </div>

    </section>

{% endblock %}
{% block javascripts %}

{% endblock %}

templates/basic/videos.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <link href="https://vjs.zencdn.net/7.2.3/video-js.css" rel="stylesheet">
    {{ include('global/header-user.html.twig') }}
{#    <form action="{{ path('buscador') }}">#}
{#        <input id="query" name="query" />#}
{#    </form>#}

    <div class="container-fluid px-0 bg-blue min-vh-100  pb-footer bg-videos">
        <div class="preview_mob">
            <img src="{{  destacado.imagen }}" alt="">
            <a class="call-popUp bt-2" data-wallpaper="{{  destacado.imagen }}" data-video="{{ destacado.idVimeo }}" data-domain="{{ qi.setting('bucket_s3') }}" data-aws="{{ destacado.awsUrl }}" data-titulo="{{ qi.slugify(destacado.titulo) }}">
                Reproducir
            </a>
        </div>
        <div class="preview_web">
            {#Este deberia ser un tipo especial de video con:
             *texto enriquecido
             *2 espacios para links de vimeo
                Uno para el preview y otro para el video completo al que enlaza
             *
             #}
            <img class="wallpaper" src='{{ destacado.imagen }}'>
            {% if destacado.awsPreviewUrl %}
                <video muted="muted" width="640" height="270"  id="video_destacado" data-video="{{ qi.setting('bucket_s3') }}{{ destacado.awsPreviewUrl }}"></video>
            {% else %}
                <iframe src="https://player.vimeo.com/video/{{ destacado.idPreviewVimeo }}?color=09a6a7&title=0&byline=0&portrait&autoplay=1&controls=0"  frameborder="0" allow="autoplay"></iframe>
            {% endif %}
            <div class="textos">
                <img src="{{  destacado.categoria.imagen }}" alt="">
                <h2>{{ destacado.titulo }}</h2>
                <p>
                    {{ destacado.resumen }}
                </p>
                <a class="call-popUp pause-main bt-2" data-wallpaper="{{  destacado.imagen }}" data-video="{{ destacado.idVimeo }}" data-domain="{{ qi.setting('bucket_s3') }}" data-aws="{{ destacado.awsUrl }}" data-titulo="{{ qi.slugify(destacado.titulo) }}">
                    Reproducir
                </a>
            </div>
        </div>
        {% for item in categorias %}
            {% if item.id == 8 %}
            {% else %}
                <section class="categorias" id="cat{{ item.id }}">
                    <div class="title">
        {#                <img src="{{ item.imagen.ruta() }}"/>#}
                        <h2>{{ item.nombre }}</h2>
                    </div>
                    <div class="s-g py-2 d-flex justify-content-between align-items-center">
                        <div class="swiper-button-prev"></div>
                        <div class="container-s-g">
                            <div class="swiper-wrapper">
                                {% for video in qi.videosCategoria(item.id) %}
                                        <div class="swiper-slide">
                                            <a class="item call-popUp" data-wallpaper="{{  video.imagen }}" data-video="{{ video.idVimeo }}" data-domain="{{ qi.setting('bucket_s3') }}" data-aws="{{ video.awsUrl }}" data-titulo="{{ qi.slugify(video.titulo) }}">
                                                <img class="w-100" src="{{ video.imagen }}"/>
                                                <span class="new">NEW!</span>
                                            </a>
                                        </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="swiper-button-next"></div>
                    </div>
                </section>
            {% endif %}
        {% endfor %}
        <div class="friends" style="background-image: url({{ asset('images/bg-friends.png') }});">
            <img src="{{ asset('images/top-friends.png') }}" alt="" class="top">
            <div class="vids">
{#                {% for i in 1..11 %}#}
                {% for video in qi.VideosCategoria(8)%}
                    <a class="video-circ call-popUp" data-wallpaper="{{  video.imagen }}" data-video="{{ video.idVimeo }}" data-domain="{{ qi.setting('bucket_s3') }}" data-aws="{{ video.awsUrl }}" data-titulo="{{ qi.slugify(video.titulo) }}">
                        <img src="{{  video.imagen }}"/>
                    </a>
                {% endfor %}
{#                {% endfor %}#}
            </div>
        </div>
    </div>



{% endblock %}

{% block javascripts %}
    {% for message in app.flashes('info') %}
        <script>Swal.fire('{{ message }}')</script>
    {% endfor %}
    <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
    <script>

        $(function () {
            var video = document.getElementById('video_destacado');
            const $video = $('#video_destacado');
            var videoSrc = $video.data("video") || $video.attr("src");
            if (videoSrc) {
                if (Hls.isSupported()) {
                    var hls = new Hls();
                    hls.loadSource(videoSrc);
                    hls.attachMedia(video);
                    hls.on(Hls.Events.MANIFEST_PARSED, function () {
                        video.play();

                        console.log("play video");
                    });
                } else if (video.canPlayType('application/vnd.apple.mpegurl')) {
                    video.src = videoSrc;
                    video.addEventListener('loadedmetadata', function () {
                        console.log("play video else if");
                        video.play();
                    });
                }
            }


            var players = []
            $('.preview_web').each(function() {

                    console.log('test1', players);

                    players.push({
                        player: new Vimeo.Player($(this).find("iframe").get(0)),
                        top: $(this).position().top,
                        status: "paused"
                    });
                    console.log('test2', players);

            });
            var viewportHeight = $(window).height();

            if( !$(".preview_web").is(":visible")) {
                for(var i=0; i<players.length;i++) {
                    players[i].status = "pause";
                    players[i].player["pause"]();
                }
            }
            $(window).on('scroll', function() {
                var scrollPos = $(window).scrollTop();
                for(var i=0; i<players.length;i++) {
                    var elementFromTop = players[i].top - scrollPos;
                    var status = (elementFromTop > 1000 && elementFromTop < players[i].top + viewportHeight + 500) ? "play" : "pause";
                    if(players[i].status != status) {

                        players[i].status = status;
                        players[i].player[status]();
                    }
                }
                video.stop();
            });
            $('.pause-main').click(function () {
                players[0].status = 'pause';
                $('.wallpaper').removeClass('hidden');

            });
            setTimeout(function(){
                $('.wallpaper').addClass('hidden');
            }, 1500);
        })
    </script>
{% endblock %}